#spring.application.name=Spring
#spring.h2.console.enabled=ture
#spring.datasource.url=jdbc:h2:mem:test
spring:
  application:
    name: Spring

  datasource:
    url: jdbc:h2:file:C:/Users/DELL/test;IFEXISTS=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create