spring.application.name=Spring
spring.h2.console.enabled=ture
spring.datasource.url=jdbc:h2:mem:test
#spring:
#  application:
#    name: Spring
#    datasource:
#      url: jdbc:h2:mem:test
#  h2:
#    console:
#      enabled: true

